Fix shadowed variable
mandiant/capa pull request #1400
Opened 2023-03-24 16:59 UTC by manasghandat

### Checklist

- [x] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

2023-03-26 09:33 UTC, williballenthin commented on capa/render/proto/__init__.py
> +                            ),
thanks for making these changes

2023-03-26 09:33 UTC, williballenthin commented on capa/render/proto/__init__.py
> +        return frzf.ImportFeature(import_=ff.import_, description=ff.description or None)  # type: ignore
please add comments describing why we're overriding mypy

2023-03-26 09:33 UTC, williballenthin commented on capa/render/proto/__init__.py
> +    # Mypy is unable to recognise arguments due to alias
these comments are good

2023-03-26 09:34 UTC, williballenthin commented on capa/render/proto/capa_pb2.py
please revert changes to these autogenerated files (`*_py2.*`). they are created by the protobuf compiler, not by hand, so we should try to keep them pristine.

2023-03-26 09:35 UTC, williballenthin requested changes
few requests inline

2023-03-27 11:17 UTC, closed without merging

2023-03-28 08:30 UTC, mr-tz commented
what happened with the close here?

2023-03-28 10:12 UTC, williballenthin commented
no, i must have hit the close button by mistake 🤦🏼 
and since the branch got deleted i'll have to recreate the changes and attribute them to @manasghandat 
sorry about that!

2023-03-28 15:50 UTC, mr-tz commented
oh no, @manasghandat if you still have the changes handy please open a new PR

2023-03-28 16:46 UTC, manasghandat commented
@mr-tz @williballenthin Can you please create a branch so that I can commit to or should I commit to the main branch?

2023-03-28 20:07 UTC, williballenthin commented
Sorry for the mistake here. I’ll reconstruct the code proposed by @manasghandat and find a way to reopen this PR or create a new one.

2023-03-29 04:38 UTC, manasghandat commented
@williballenthin  I do have to code and I have made the recommended changes too. It will be great if you could just make a branch for me to commit to.

2023-03-29 12:49 UTC, williballenthin commented
please see the new PR in #1412 and continue work there.  i think outstanding are a few mypy override comments and reverting changes to autogenerated files.