add a Dynamic extractor interface
mandiant/capa pull request #1528
Opened 2023-06-09 08:06 UTC by yelhamer

This is the parent branch of the cape-dynamic-extractor and cuckoo-dynamic extractor; The two will ensue later on. It defined the interface that all dynamic sandbox-based feature extractors should implement.

### Checklist

- [ ] No CHANGELOG update needed

- [x ] No new tests needed

- [ ] No documentation update needed

2023-06-09 08:32 UTC, mr-tz reviewed
looks promising :) sorry if I jumped into review too quickly, I'm just very excited

2023-06-09 08:32 UTC, mr-tz commented on capa/features/extractors/base_extractor.py
> +    def get_threads(self, ph: ProcessHandle) -> Iterator[ProcessHandle]:
```suggestion
    def get_threads(self, ph: ProcessHandle) -> Iterator[ThreadHandle]:
```

2023-06-09 08:32 UTC, mr-tz commented on capa/features/extractors/base_extractor.py
> +        - files/registris interacted with
```suggestion
        - file/registry interactions
```

2023-06-14 08:22 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +    pid: int
tracked in #1547

2023-06-14 08:23 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +
tracked in #1548

2023-06-14 08:24 UTC, williballenthin commented on README.md
>  [![License](https://img.shields.io/badge/license-Apache--2.0-green.svg)](LICENSE.txt)
these extra changes stem from us not keeping the feature branch in sync with master. i'll do a merge from there.

2023-06-14 08:29 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +    pid: int
hm, now that i think about this: this is the abstract interface for dynamic handles, which means that all implementors *must* be able to provide this data. if we're not sure that its available, then we should rely on implementors to subclass and/or use the `inner` property.

with that in mind, i think we should at least remove ppid. im not sure about using pid/tid. for the time being, lets keep this, with the understanding that as we add support for other sandboxes, we might have to change this interface.
```suggestion
    pid: int
```

2023-06-14 08:29 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +
```suggestion
```

default implementation doesn't have to be specified

2023-06-14 08:30 UTC, williballenthin requested changes
two minor suggested changes, then lets merge this!

2023-06-14 08:54 UTC, williballenthin approved these changes

2023-06-14 08:57 UTC, williballenthin requested changes
sorry, more small tweaks. i'll try to merge them directly if i have perms.

2023-06-14 08:57 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +from typing import Any, Dict, Tuple, Union, Iterator, TextIO, BinaryIO
```suggestion
from typing import Any, Dict, Tuple, Union, Iterator
```

2023-06-14 08:57 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +        ppid: parent process id
```suggestion
```

2023-06-14 08:57 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +            ph: parent process
```suggestion
        Enumerate processes in the trace.
```

2023-06-14 08:57 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +            ph: parent process
```suggestion
        Enumerate threads in the given process.
```

2023-06-14 08:58 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +from typing import Any, Dict, Tuple, Union, Iterator, TextIO, BinaryIO
i dont know why our code style linter didn't catch this?

2023-06-14 08:58 UTC, williballenthin commented on capa/features/extractors/base_extractor.py
> +from typing import Any, Dict, Tuple, Union, Iterator, TextIO, BinaryIO
oh cause it was blocked by the changelog checker

2023-06-14 09:00 UTC, williballenthin approved these changes

2023-06-14 09:00 UTC, merged