Ghidra fixes
mandiant/capa pull request #1733
Opened 2023-08-17 17:28 UTC by colton-gabertan

### Checklist

- [X] No CHANGELOG update needed

- [ ] No new tests needed

- [ ] No documentation update needed

# Ghidra: Feature Extraction Adjustments
---

This PR is used to make changes to ghidra feature extractors to pass CI and address differences between backends.

2023-08-22 20:06 UTC, mike-hunhoff commented on capa/features/extractors/ghidra/insn.py
> +                        continue
If I'm following, these checks avoid extracting `4` from instructions like `LEA EBX, [ECX + EAX*0x4]`? Can we simply check if the  instruction is `LEA` and `len(insn.getOpObjects[1])` != 4? If not, is it guarenteed that `insn.toString()` uses hex representation for numbers? e.g. if a user sets the disassembly view to base 10 representation.

2023-08-23 11:20 UTC, colton-gabertan commented on capa/features/extractors/ghidra/helpers.py
> +
Yea, `isStackReference()` seems to only be handling it on instructions that directly reference the stack such as `[EBP + local_18]`, but it wouldn't pick up on instructions that directly handled the base pointer alone.

2023-08-23 15:42 UTC, mike-hunhoff commented on capa/features/extractors/ghidra/global_.py
> +            pb_arr = pb_arr + capa.features.extractors.ghidra.helpers.fix_byte(fbytes.getOriginalByte(i))
Hmm this is an interesting problem that we may be able to work with the Jep developers to address in the future. Please open a new Ghidrathon issue describing what you have found here and I'll likely float this upstream.

2023-08-23 15:43 UTC, mike-hunhoff commented on capa/features/extractors/ghidra/helpers.py
> +
For the latter, something like `add ebp, 4`?

2023-08-23 18:06 UTC, mike-hunhoff requested changes
Great updates! A couple of questions for you to address 🚀

2023-08-23 18:06 UTC, mike-hunhoff commented on capa/features/extractors/ghidra/helpers.py
> +                    ref = thunk_jmp.getAddress(i)
Using this loop we always choose the last operand that is an address. Can we skip the loop and jump straight to checking if the last operand is an address?

2023-08-23 18:11 UTC, colton-gabertan commented on capa/features/extractors/ghidra/helpers.py
> +    return ref
I think we can `break` right after `ref = thunk_dat.getValue()`, since that would be the end of the thunk chain

2023-08-23 20:34 UTC, mike-hunhoff approved these changes
nice work!

2023-08-23 20:35 UTC, merged