ghidra: documentation
mandiant/capa pull request #1759
Opened 2023-08-24 20:25 UTC by colton-gabertan

### Checklist

- [X] No CHANGELOG update needed

- [X] No new tests needed

- [X] No documentation update needed

# Ghidra: Documentation
Implements #1512

2023-08-24 20:25 UTC, colton-gabertan commented
Note: PR up for now so I can see how it renders in the Github Web UI

2023-08-25 15:48 UTC, mike-hunhoff commented on README.md
> +If you use Ghidra, then you can enable the [Ghidra Backend](/capa/ghidra/). capa will extract features directly from your Ghidra databases and help you identify the functionality of the programs that
```suggestion
If you use Ghidra, then you can use the [Ghidra Backend](/capa/ghidra/). capa will extract features directly from your Ghidra databases and help you identify the functionality of the programs that you import or are already working on. 
```

2023-08-25 15:57 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +| capa | `>= 6.1.0` | `<url for capa release>`
```suggestion
```

2023-08-25 15:57 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +| capa | `>= 6.1.0` | `<url for capa release>`
User's should already expect to have capa installed by this point.

2023-08-25 15:57 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +**Required Dependencies:**
```suggestion
**Dependencies:**
```

2023-08-25 15:58 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +| Ghidrathon | `>= 3.0.0` | https://github.com/mandiant/Ghidrathon/tree/v3.0.0 |
```suggestion
| Ghidrathon | `>= 3.0.0` | https://github.com/mandiant/Ghidrathon |
```

2023-08-25 15:58 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +| Ghidrathon | `>= 3.0.0` | https://github.com/mandiant/Ghidrathon/tree/v3.0.0 |
With this change we do not need to update the link with each new Ghidrathon release.

2023-08-25 16:03 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +| capa | `>= 6.1.0` | `<url for capa release>`
We need to add directions for how a user must install capa in order to use it from Ghidra e.g. see the installation steps [specified for the IDA plugin.](https://github.com/mandiant/capa/tree/master/capa/ida/plugin#installation)

Namely, a user must:

1. Install capa as a library (see IDA plugin for command)
2. Download and extract official capa rules that matches the version of capa installed
3. Make it work with Ghidra from there

2023-08-25 16:05 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +Once Ghidrathon is configured and ready-to-go, you may now invoke capa from within Ghidra in three different ways. Each method suits different use cases of capa, and they include the `headlessAnalyze
```suggestion
Once Ghidrathon is configured, you may now invoke capa from within Ghidra in three different ways. Each method suits different use cases of capa, and they include the Ghidra's `headlessAnalyzer`, `Scripting Console`, and `Script Manger`.
```

2023-08-25 16:07 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +> **note:** You may add the `$GHIDRA_INSTALL_DIR/support` to your `$PATH` in order to call `analyzeHeadless` as a standalone program.
```suggestion
> **Note:** You may add the `$GHIDRA_INSTALL_DIR/support` to your `$PATH` in order to call `analyzeHeadless` as a standalone program.
```

2023-08-25 16:07 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +### headlessAnalyzer
```suggestion
### Ghidra's headlessAnalyzer
```

2023-08-25 16:09 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +<img src="/doc/img/ghidrathon_headless.gif">
Let's stick with static screenshots if we can, to avoid the large size of these GIFs. GIFs are also difficult to recreate when changes are made to the project.

2023-08-27 20:44 UTC, mike-hunhoff requested changes
Good job putting this together @colton-gabertan ! I've left comments for your review 🚀

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +The Ghidra feature extractor is an application of the FLARE team's open-source project, Ghidrathon, to integrate capa with Ghidra. capa is a framework that uses a well-defined collection of rules to
```suggestion
The Ghidra feature extractor is an application of the FLARE team's open-source project, Ghidrathon, to integrate capa with Ghidra using Python 3. capa is a framework that uses a well-defined collection of rules to identify capabilities in a program. You can run capa against a PE file, ELF file, or shellcode and it tells you what it thinks the program can do. For example, it might suggest that the program is a backdoor, can install services, or relies on HTTP to communicate. The Ghidra feature extractor can be used to run capa analysis on your Ghidra databases without needing access to the original binary file.
```

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +The Ghidra feature extractor is an application of the FLARE team's open-source project, Ghidrathon, to integrate capa with Ghidra. capa is a framework that uses a well-defined collection of rules to
Let's also be explicit here that this is a Python 3 project.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +./$GHIDRA_INSTALL_DIR/support/analyzeHeadless /path/to/gpr_dir/ gpr_name -process sample_name.exe_ -ScriptPath /path/to/capa_install/capa/ghidra -PostScript capa_ghidra.py "/path/to/rules/"
```suggestion
./$GHIDRA_INSTALL_DIR/support/analyzeHeadless /path/to/gpr_dir/ gpr_name -process sample_name.exe_ -ScriptPath /path/to/capa_ghidra.py/ -PostScript capa_ghidra.py "/path/to/capa/rules/"
```

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +./$GHIDRA_INSTALL_DIR/support/analyzeHeadless /path/to/gpr_dir/ gpr_name -process sample_name.exe_ -ScriptPath /path/to/capa_install/capa/ghidra -PostScript capa_ghidra.py "/path/to/rules/"
With the introduction of `capa_ghidra.py`, we no longer require users know the full path to their capa installation, just that they know the path to their local `capa_ghidra.py`.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +The syntax to both import a new file and run capa against it is:
Stated above now.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +./$GHIDRA_INSTALL_DIR/support/analyzeHeadless /path/to/gpr_dir/ gpr_name -Import /path/to/sample_name.exe_ -ScriptPath /path/to/capa_install/capa/ghidra -PostScript capa_ghidra.py "/path/to/rules/"
Let's be more explicit about what where saying here, e.g. by removing `.exe_` we don't artificially restrict users into thinking this integration only supports PE exe files.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +Successful invocation from the `Ghidra Script Manager` will look like:
```suggestion
```

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +> **Note:** In order for the Script Manager to recognize `capa_ghidra.py` you must either copy it to your Ghidra user scripts directory or update the Script Manager search path to include directory t
We should always be explicit about what a user should expect before, during, and after using our tool (even though we show this later using screen captures). Here I expand on what you had already provided to include what information they will be asked to provide during script execution and where the results go when the script is finished.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +Successful invocation from the `Ghidra Script Manager` will look like:
Covered above now.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +
Stripping out some information we can assume the user already knows, e.g. opening the code browser.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +3. Copy `capa_ghidra.py` to your Ghidra user scripts directory OR update the `Ghidra Script Manager` path to point to it.
I've found it best to place important links as close to the first time you mention them. Here, we provide the link to `capa_ghidra.py` so a user has immediate access.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +### Ghidra's headlessAnalyzer
```suggestion
### Ghidra's Headless Analyzer
```

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +To invoke capa headlessly (i.e. without the Ghidra user interface), we must call the `analyzeHeadless` script provided in your `$GHIDRA_INSTALL_DIR/support` and point it towards capa's `capa_ghidra.p
This many moving parts is a hard one to explain in a single paragraph. Let's focus on the details that are most relevant to the user.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +> **Note:** You may add the `$GHIDRA_INSTALL_DIR/support` to your `$PATH` in order to call `analyzeHeadless` as a standalone program.
Let's add additional context for the `-ScriptPath` argument to help users better understand how they can configure their environment to make these commands more streamlined.

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +If you do not have an existing ghidra project, you may also create one with the headlessAnalyzer via the `-Import` flag. Post scripts may also be ran in the same invocation.
Please correct me here but my understanding is that `-Import` can only be used to import a new sample into an _existing_ Ghidra project, but not be used to create a new Ghidra project?

2023-08-27 20:44 UTC, mike-hunhoff commented on capa/ghidra/README.md
> +> **Note:** The `/path/to/gpr_dir/` must exist before importing a new project into it.
Please see my comment above about the Ghidra projects and the `-Import` flag.

2023-08-28 02:21 UTC, merged