[ENH] Refactor format in `capa/features/extractors/dotnetfile.py`
mandiant/capa pull request #2024
Opened 2024-03-07 16:59 UTC by samadpls

Changed format order for .NET files 
closes #2022 
### Checklist

- [X] No CHANGELOG update needed

- [X] No new tests needed

- [X] No documentation update needed

2024-03-11 20:36 UTC, mike-hunhoff reviewed
Looks good @samadpls . Please verify that the `-vv` output from capa's standalone tool lists `.NET` as the format in the metadata section by posting the output here. You can use one of the `.NET` samples from [`capa/test-files`](https://github.com/mandiant/capa-testfiles/tree/master/dotnet).

2024-03-15 20:39 UTC, samadpls commented
Hello @mike-hunhoff , while setting up the locally im facing following issue
```bash
capa -vv /media/samadpls/ubuntu/download/1c444ebeba24dcba8628b7dfe5fec7c6.exe_
ERROR:capa:[Errno 28] No space left on device: '/home/samadpls/.cache/capa'
ERROR:capa:Make sure your file directory contains properly formatted capa rules. You can download the standard collection of capa rules from https://github.com/mandiant/capa-rules/releases.
ERROR:capa:Please ensure you're using the rules that correspond to your major version of capa (7)
ERROR:capa:Or, for more details, see the rule set documentation here: https://github.com/mandiant/capa/blob/master/doc/rules.md
```

2024-03-16 08:37 UTC, mr-tz commented
Are you out of hard-drive space?

2024-03-16 19:30 UTC, samadpls commented
> Looks good @samadpls . Please verify that the `-vv` output from capa's standalone tool lists `.NET` as the format in the metadata section by posting the output here. You can use one of the `.NET` samples from [`capa/test-files`](https://github.com/mandiant/capa-testfiles/tree/master/dotnet).

Here the output i got after running the following command
```
format                  pe
...
create or open registry key (2 matches, only showing first match of library rule)
...
save image in .NET
...
```
<details>
<summary>show more</summary>
```bash
capa -vv -r E:\capa-rules-7.0.1\capa-rules-7.0.1  1c444ebeba24dcba8628b7dfe5fec7c6.exe
md5                     1c444ebeba24dcba8628b7dfe5fec7c6
sha1                    ebdec120fbbdbff28ebd6accc85d05f7ccabf461
sha256                  a9f9e5a30cc858dc135ec428cdd68cb06143732e5c62c4dc4b359c8abc11d74b
path                    E:/extraproj/capa/1c444ebeba24dcba8628b7dfe5fec7c6.exe
timestamp               2024-03-16 23:55:17.310730
capa version            7.0.1
os                      any
format                  pe
arch                    any
analysis                static
extractor               DnfileFeatureExtractor
base address            global
rules                   E:/capa-rules-7.0.1/capa-rules-7.0.1
function count          150
library function count  0
total feature count     4309

create or open registry key (2 matches, only showing first match of library rule)
author  michael.hunhoff@mandiant.com, anushka.virgaonkar@mandiant.com
scope   basic block
mbc     Operating System::Registry::Create Registry Key [C0036.004], Operating System::Registry::Open Registry Key [C0036.003]
basic block @ token(0x6000062) in function token(0x6000062)
  or:
    api: Microsoft.Win32.RegistryKey::OpenSubKey @ token(0x6000062)+0xB

save image in .NET
namespace  collection
author     michael.hunhoff@mandiant.com
scope      function
function @ token(0x600006D)
  and:
    api: System.Drawing.Image::Save @ token(0x600006D)+0x11
    optional:
      class: System.Drawing.Imaging.ImageFormat @ token(0x600006D)+0xC

capture screenshot
namespace  collection/screenshot
author     moritz.raabe@mandiant.com, @_re_fox, michael.hunhoff@mandiant.com
scope      function
att&ck     Collection::Screen Capture [T1113]
mbc        Collection::Screen Capture::WinAPI [E1113.m01]
function @ token(0x6000073)
  or:
    and:
      or:
        api: GetWindowDC @ token(0x6000073)+0x1
      or:
        api: BitBlt @ token(0x6000073)+0x63
      api: CreateCompatibleDC @ token(0x6000073)+0x39
      api: CreateCompatibleBitmap @ token(0x6000073)+0x43

send data (2 matches)
namespace    communication
author       william.ballenthin@mandiant.com, joakim@intezer.com
scope        function
mbc          Command and Control::C2 Communication::Send Data [B0030.001]
description  all known techniques for sending data to a potential C2 server
function @ token(0x6000096)
  or:
    and:
      os: windows
      or:
        match: send HTTP request @ token(0x6000096)
          or:
            api: System.Net.WebRequest::GetResponse @ token(0x6000096)+0x4D0
function @ token(0x600009B)
  or:
    and:
      os: windows
      or:
        match: send HTTP request @ token(0x600009B)
          or:
            api: System.Net.WebRequest::GetResponse @ token(0x600009B)+0x7C

set web proxy in .NET
namespace  communication/http
author     michael.hunhoff@mandiant.com
scope      function
function @ token(0x6000096)
  and:
    property/write: System.Net.WebRequest::Proxy @ token(0x6000096)+0x20

create HTTP request (2 matches)
namespace  communication/http/client
author     michael.hunhoff@mandiant.com, anushka.virgaonkar@mandiant.com
scope      function
mbc        Communication::HTTP Communication::Create Request [C0002.012]
function @ token(0x6000096)
  and:
    or:
      api: System.Net.WebRequest::Create @ token(0x6000096)+0x7
function @ token(0x600009B)
  and:
    or:
      api: System.Net.WebRequest::Create @ token(0x600009B)+0x6E

receive HTTP response (2 matches)
namespace  communication/http/client
author     michael.hunhoff@mandiant.com
scope      function
mbc        Communication::HTTP Communication::Get Response [C0002.017]
function @ token(0x6000096)
  or:
    api: System.Net.WebRequest::GetResponse @ token(0x6000096)+0x4D0
function @ token(0x600009B)
  or:
    api: System.Net.WebRequest::GetResponse @ token(0x600009B)+0x7C

send HTTP request (2 matches)
namespace  communication/http/client
author     moritz.raabe@mandiant.com, michael.hunhoff@mandiant.com
scope      function
mbc        Communication::HTTP Communication::Send Request [C0002.003]
function @ token(0x6000096)
  or:
    api: System.Net.WebRequest::GetResponse @ token(0x6000096)+0x4D0
function @ token(0x600009B)
  or:
    api: System.Net.WebRequest::GetResponse @ token(0x600009B)+0x7C

send request in .NET
namespace  communication/http/client
author     anushka.virgaonakr@mandiant.com
scope      function
att&ck     Command and Control::Application Layer Protocol::Web Protocols [T1071.001]
mbc        Communication::HTTP Communication::Send Request [C0002.003]
function @ token(0x6000096)
  and:
    api: System.IO.Stream::Write @ token(0x6000096)+0x2B0, token(0x6000096)+0x314, token(0x6000096)+0x322, token(0x6000096)+0x341, and 8 more...
    api: System.IO.Stream::Close @ token(0x6000096)+0x435, token(0x6000096)+0x4CA, token(0x6000096)+0x4FF
    or:
      api: System.Net.WebRequest::GetRequestStream @ token(0x6000096)+0x2A0

act as TCP client
namespace  communication/tcp/client
author     william.ballenthin@mandiant.com, michael.hunhoff@mandiant.com
scope      function
mbc        Communication::Socket Communication::TCP Client [C0001.008]
function @ token(0x600008A)
  or:
    api: System.Net.Sockets.TcpClient::ctor @ token(0x600008A)+0x26

decode data using Base64 in .NET
namespace  data-manipulation/encoding/base64
author     michael.hunhoff@mandiant.com
scope      function
att&ck     Defense Evasion::Deobfuscate/Decode Files or Information [T1140]
mbc        Data::Decode Data::Base64 [C0053.001]
function @ token(0x6000023)
  or:
    api: System.Convert::FromBase64String @ token(0x6000023)+0xC

encode data using Base64 (11 matches)
namespace  data-manipulation/encoding/base64
author     moritz.raabe@mandiant.com, anushka.virgaonkar@mandiant.com, michael.hunhoff@mandiant.com
scope      function
att&ck     Defense Evasion::Obfuscated Files or Information [T1027]
mbc        Defense Evasion::Obfuscated Files or Information::Encoding-Standard Algorithm [E1027.m02], Data::Encode Data::Base64 [C0026.001]function @ token(0x600001B)
  or:
    api: System.Convert::ToBase64String @ token(0x600001B)+0x30
function @ token(0x6000028)
  or:
    api: System.Convert::ToBase64String @ token(0x6000028)+0x40
function @ token(0x600002C)
  or:
    api: System.Convert::ToBase64String @ token(0x600002C)+0x17
function @ token(0x600002F)
  or:
    api: System.Convert::ToBase64String @ token(0x600002F)+0x40
function @ token(0x6000034)
  or:
    api: System.Convert::ToBase64String @ token(0x6000034)+0x40
function @ token(0x6000039)
  or:
    api: System.Convert::ToBase64String @ token(0x6000039)+0x40
function @ token(0x600003E)
  or:
    api: System.Convert::ToBase64String @ token(0x600003E)+0x40
function @ token(0x6000048)
  or:
    api: System.Convert::ToBase64String @ token(0x6000048)+0x40
function @ token(0x600004E)
  or:
    api: System.Convert::ToBase64String @ token(0x600004E)+0x40
function @ token(0x6000064)
  or:
    api: System.Convert::ToBase64String @ token(0x6000064)+0x17
function @ token(0x60000A0)
  or:
    api: System.Convert::ToBase64String @ token(0x60000A0)+0x3E

hash data with MD5
namespace   data-manipulation/hashing/md5
author      moritz.raabe@mandiant.com, anushka.virgaonkar@mandiant.com, michael.hunhoff@mandiant.com
scope       function
mbc         Cryptography::Cryptographic Hash::MD5 [C0029.001]
references  https://github.com/rwfpl/rewolf-x86-virtualizer/blob/master/src/test_app/main.cpp
function @ token(0x600001D)
  [...]

2024-03-17 00:31 UTC, samadpls commented
> Are you out of hard-drive space?

Hi @mr-tz  , thanks for noticing. Yes, I noticed that my cache was full somehow, so I ran it on Windows and got the log

2024-03-18 16:09 UTC, mike-hunhoff commented
> > Looks good @samadpls . Please verify that the `-vv` output from capa's standalone tool lists `.NET` as the format in the metadata section by posting the output here. You can use one of the `.NET` samples from [`capa/test-files`](https://github.com/mandiant/capa-testfiles/tree/master/dotnet).
> 
> @mike-hunhoff , Sorry for responding late; I was busy with academic workk. Here the output i got after running the following command
> 
> ```
> format                  pe
> ...
> create or open registry key (2 matches, only showing first match of library rule)
> ...
> save image in .NET
> ...
> ```
> 
> full log
> ```
> capa -vv -r E:\capa-rules-7.0.1\capa-rules-7.0.1  1c444ebeba24dcba8628b7dfe5fec7c6.exe
> md5                     1c444ebeba24dcba8628b7dfe5fec7c6
> sha1                    ebdec120fbbdbff28ebd6accc85d05f7ccabf461
> sha256                  a9f9e5a30cc858dc135ec428cdd68cb06143732e5c62c4dc4b359c8abc11d74b
> path                    E:/extraproj/capa/1c444ebeba24dcba8628b7dfe5fec7c6.exe
> timestamp               2024-03-16 23:55:17.310730
> capa version            7.0.1
> os                      any
> format                  pe
> arch                    any
> analysis                static
> extractor               DnfileFeatureExtractor
> base address            global
> rules                   E:/capa-rules-7.0.1/capa-rules-7.0.1
> function count          150
> library function count  0
> total feature count     4309
> 
> [...]
> ```


Thank you for providing the output. Following the changes that you've made in this PR I'd expect capa's output to list `format: dotnet`, not `format: pe` e.g. expected output for .NET file:
```
capa -vv -r E:\capa-rules-7.0.1\capa-rules-7.0.1  1c444ebeba24dcba8628b7dfe5fec7c6.exe
md5                     1c444ebeba24dcba8628b7dfe5fec7c6
sha1                    ebdec120fbbdbff28ebd6accc85d05f7ccabf461
sha256                  a9f9e5a30cc858dc135ec428cdd68cb06143732e5c62c4dc4b359c8abc11d74b
path                    E:/extraproj/capa/1c444ebeba24dcba8628b7dfe5fec7c6.exe
timestamp               2024-03-16 23:55:17.310730
capa version            7.0.1
os                      any
format                  dotnet
arch                    any
```

I'm unsure based solely on the output of command whether you're running the existing capa standalone tool or capa w/ the changes that you've made in this PR. Can you confirm that you have [installed capa locally for development](https://github.com/mandiant/capa/blob/master/doc/installation.md#method-3-inspecting-the-capa-source-code) and that you are running capa with the changes that you've made in this PR?

2024-03-18 19:00 UTC, samadpls commented
@mike-hunhoff, you were right. I was in the master branch and running the command. I apologize for the oversight
here is the expected log
```bash
capa 1c444ebeba24dcba8628b7dfe5fec7c6.exe_ -vv -r ./rules/
md5                     1c444ebeba24dcba8628b7dfe5fec7c6
sha1                    ebdec120fbbdbff28ebd6accc85d05f7ccabf461
sha256                  a9f9e5a30cc858dc135ec428cdd68cb06143732e5c62c4dc4b359c8abc11d74b
path                    E:/extraproj/capa/1c444ebeba24dcba8628b7dfe5fec7c6.exe_
timestamp               2024-03-18 23:54:18.048229
capa version            7.0.1
os                      any
format                  dotnet
arch                    any
analysis                static
extractor               DnfileFeatureExtractor
base address            global
rules                   E:/extraproj/capa/rules
function count          150
library function count  0
total feature count     4309
[ .... ]
```
<details>
<summary>full log</summary>

```
capa 1c444ebeba24dcba8628b7dfe5fec7c6.exe_ -vv -r ./rules/
md5                     1c444ebeba24dcba8628b7dfe5fec7c6
sha1                    ebdec120fbbdbff28ebd6accc85d05f7ccabf461
sha256                  a9f9e5a30cc858dc135ec428cdd68cb06143732e5c62c4dc4b359c8abc11d74b
path                    E:/extraproj/capa/1c444ebeba24dcba8628b7dfe5fec7c6.exe_
timestamp               2024-03-18 23:54:18.048229
capa version            7.0.1
os                      any
format                  dotnet
arch                    any
analysis                static
extractor               DnfileFeatureExtractor
base address            global
rules                   E:/extraproj/capa/rules
function count          150
library function count  0
total feature count     4309

create or open registry key (2 matches, only showing first match of library rule)       
author  michael.hunhoff@mandiant.com, anushka.virgaonkar@mandiant.com
scope   basic block
mbc     Operating System::Registry::Create Registry Key [C0036.004], Operating System::Registry::Open Registry Key [C0036.003]
basic block @ token(0x6000062) in function token(0x6000062)
  or:
    api: Microsoft.Win32.RegistryKey::OpenSubKey @ token(0x6000062)+0xB

save image in .NET
namespace  collection
author     michael.hunhoff@mandiant.com
scope      function
function @ token(0x600006D)
  and:
    api: System.Drawing.Image::Save @ token(0x600006D)+0x11
    optional:
      class: System.Drawing.Imaging.ImageFormat @ token(0x600006D)+0xC

capture screenshot
namespace  collection/screenshot
author     moritz.raabe@mandiant.com, @_re_fox, michael.hunhoff@mandiant.com
scope      function
att&ck     Collection::Screen Capture [T1113]
mbc        Collection::Screen Capture::WinAPI [E1113.m01]
function @ token(0x6000073)
  or:
    and:
      or:
        api: GetWindowDC @ token(0x6000073)+0x1
      or:
        api: BitBlt @ token(0x6000073)+0x63
      api: CreateCompatibleDC @ token(0x6000073)+0x39
      api: CreateCompatibleBitmap @ token(0x6000073)+0x43

send data (2 matches)
namespace    communication
author       william.ballenthin@mandiant.com, joakim@intezer.com
scope        function
mbc          Command and Control::C2 Communication::Send Data [B0030.001]
description  all known techniques for sending data to a potential C2 server
function @ token(0x6000096)
  or:
    and:
      os: windows
      or:
        match: send HTTP request @ token(0x6000096)
          or:
            api: System.Net.WebRequest::GetResponse @ token(0x6000096)+0x4D0
function @ token(0x600009B)
  or:
    and:
      os: windows
      or:
        match: send HTTP request @ token(0x600009B)
          or:
            api: System.Net.WebRequest::GetResponse @ token(0x600009B)+0x7C

set web proxy in .NET
namespace  communication/http
author     michael.hunhoff@mandiant.com
scope      function
function @ token(0x6000096)
  and:
    property/write: System.Net.WebRequest::Proxy @ token(0x6000096)+0x20

create HTTP request (2 matches)
namespace  communication/http/client
author     michael.hunhoff@mandiant.com, anushka.virgaonkar@mandiant.com
scope      function
mbc        Communication::HTTP Communication::Create Request [C0002.012]
function @ token(0x6000096)
  and:
    or:
      api: System.Net.WebRequest::Create @ token(0x6000096)+0x7
function @ token(0x600009B)
  and:
    or:
      api: System.Net.WebRequest::Create @ token(0x600009B)+0x6E

receive HTTP response (2 matches)
namespace  communication/http/client
author     michael.hunhoff@mandiant.com
scope      function
mbc        Communication::HTTP Communication::Get Response [C0002.017]
function @ token(0x6000096)
  or:
    api: System.Net.WebRequest::GetResponse @ token(0x6000096)+0x4D0
function @ token(0x600009B)
  or:
    api: System.Net.WebRequest::GetResponse @ token(0x600009B)+0x7C

send HTTP request (2 matches)
namespace  communication/http/client
author     moritz.raabe@mandiant.com, michael.hunhoff@mandiant.com
scope      function
mbc        Communication::HTTP Communication::Send Request [C0002.003]
function @ token(0x6000096)
  or:
    api: System.Net.WebRequest::GetResponse @ token(0x6000096)+0x4D0
function @ token(0x600009B)
  or:
    api: System.Net.WebRequest::GetResponse @ token(0x600009B)+0x7C

send request in .NET
namespace  communication/http/client
author     anushka.virgaonakr@mandiant.com
scope      function
att&ck     Command and Control::Application Layer Protocol::Web Protocols [T1071.001]
mbc        Communication::HTTP Communication::Send Request [C0002.003]
function @ token(0x6000096)
  and:
    api: System.IO.Stream::Write @ token(0x6000096)+0x2B0, token(0x6000096)+0x314, token(0x6000096)+0x322, token(0x6000096)+0x341, and 8 more...
    api: System.IO.Stream::Close @ token(0x6000096)+0x435, token(0x6000096)+0x4CA, token(0x6000096)+0x4FF
    or:
      api: System.Net.WebRequest::GetRequestStream @ token(0x6000096)+0x2A0

act as TCP client
namespace  communication/tcp/client
author     william.ballenthin@mandiant.com, michael.hunhoff@mandiant.com
scope      function
mbc        Communication::Socket Communication::TCP Client [C0001.008]
function @ token(0x600008A)
  or:
    api: System.Net.Sockets.TcpClient::ctor @ token(0x600008A)+0x26

decode data using Base64 in .NET
namespace  data-manipulation/encoding/base64
author     michael.hunhoff@mandiant.com
scope      function
att&ck     Defense Evasion::Deobfuscate/Decode Files or Information [T1140]
mbc        Data::Decode Data::Base64 [C0053.001]
function @ token(0x6000023)
  or:
    api: System.Convert::FromBase64String @ token(0x6000023)+0xC

encode data using Base64 (11 matches)
namespace  data-manipulation/encoding/base64
author     moritz.raabe@mandiant.com, anushka.virgaonkar@mandiant.com, michael.hunhoff@mandiant.com
scope      function
att&ck     Defense Evasion::Obfuscated Files or Information [T1027]
mbc        Defense Evasion::Obfuscated Files or Information::Encoding-Standard Algorithm [E1027.m02], Data::Encode Data::Base64 [C0026.001]
function @ token(0x600001B)
  or:
    api: System.Convert::ToBase64String @ token(0x600001B)+0x30
function @ token(0x6000028)
  or:
    api: System.Convert::ToBase64String @ token(0x6000028)+0x40
function @ token(0x600002C)
  or:
    api: System.Convert::ToBase64String @ token(0x600002C)+0x17
function @ token(0x600002F)
  or:
    api: System.Convert::ToBase64String @ token(0x600002F)+0x40
function @ token(0x6000034)
  or:
    api: System.Convert::ToBase64String @ token(0x6000034)+0x40
function @ token(0x6000039)
  or:
    api: System.Convert::ToBase64String @ token(0x6000039)+0x40
function @ token(0x600003E)
  or:
    api: System.Convert::ToBase64String @ token(0x600003E)+0x40
function @ token(0x6000048)
  or:
    api: System.Convert::ToBase64String @ token(0x6000048)+0x40
function @ token(0x600004E)
  or:
    api: System.Convert::ToBase64String @ token(0x600004E)+0x40
function @ token(0x6000064)
  or:
    api: System.Convert::ToBase64String @ token(0x6000064)+0x17
function @ token(0x60000A0)
  or:
    api: System.Convert::ToBase64String @ token(0x [...]

2024-03-19 15:50 UTC, mike-hunhoff requested changes
Looking food @samadpls . One small change to add and we can merge 🚀

2024-03-20 15:50 UTC, mike-hunhoff approved these changes
LGTM 🚀

2024-03-20 17:07 UTC, merged