Restrict signature debug logging to vivisect backend
mandiant/capa pull request #2044
Opened 2024-04-02 06:42 UTC by acelynnzhang

I noticed that signatures will only load when the backend is vivisect:
https://github.com/mandiant/capa/blob/7debc54dbd90372af8f4e3b1819fe632afdaa3fa/capa/main.py#L695-L698

I moved the debug logging from `handle_common_args` to `get_signatures_from_cli`, so it's only printed when the signatures are actually used. This means that other backends don't need the default signatures directory to exist.

Closes #1875

### Checklist

- [x] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

2024-04-02 13:18 UTC, mr-tz commented on capa/main.py
> +
let's move this outside of the try block, otherwise looks great

2024-04-02 13:18 UTC, mr-tz requested changes
see inline comment, then good to go

2024-04-02 16:13 UTC, acelynnzhang commented
> see inline comment, then good to go

is this good? thanks!

2024-04-02 16:18 UTC, williballenthin approved these changes
thanks!

2024-04-03 05:20 UTC, mr-tz approved these changes
thank you

2024-04-03 05:20 UTC, merged