Fixed infinite loop when parsing dotnet TypeRef table
mandiant/capa pull request #2045
Opened 2024-04-02 08:07 UTC by x9090

There was a `TypeRef` table infinite loop issue when dotnet parser parsing a crafted dotnet sample with ref index refer to each other:

![problematic-dotnet](https://github.com/mandiant/capa/assets/4924242/7c68d84f-c76b-4c7b-a5ca-6c52b3c3925e)
 
Let me know if you need the sample for testing, I could upload it here.

### Checklist

- [ ] No CHANGELOG update needed

- [ ] No new tests needed

- [ ] No documentation update needed

2024-04-15 16:11 UTC, mike-hunhoff commented
> There was a `TypeRef` table infinite loop issue when dotnet parser parsing a crafted dotnet sample with ref index refer to each other:
> 
> ![problematic-dotnet](https://private-user-images.githubusercontent.com/4924242/318694461-7c68d84f-c76b-4c7b-a5ca-6c52b3c3925e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTc2NTIsIm5iZiI6MTcxMzE5NzM1MiwicGF0aCI6Ii80OTI0MjQyLzMxODY5NDQ2MS03YzY4ZDg0Zi1jNzZiLTRjN2ItYTVjYS02YzUyYjNjMzkyNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMTYwOTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI5ODk4M2I0N2MwYWJkOTA4Yjk0MDM2ZWRiNDUyMjQ3ZDI5ZjUzMGFkYTc1MGE5MGVmNTc0ZjY5MmY1YWY0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vLb_k65phIjWBydt-_f45T6Bhoudz32101oUr2BPtEg)   Let me know if you need the sample for testing, I could upload it here.
> 
> ### Checklist
> * [x]  No CHANGELOG update needed
> 
> * [x]  No new tests needed
> 
> * [x]  No documentation update needed

Hi @x9090 , thank you for the find and suggested fix - apologies for not getting back to you sooner! Please update the sample for testing and review the CLA requirements so we can move this PR forward.

2024-04-15 16:17 UTC, mike-hunhoff requested changes
Thanks @x9090 , I've left comments for your review 🚀

2024-04-15 16:17 UTC, mike-hunhoff commented on capa/features/extractors/dnfile/helpers.py
> +        typeref_tb = []
I'm not sure what `_tb` means, please add a comment or consider updating the name to something more obvious like `_visited`.

2024-04-15 16:17 UTC, mike-hunhoff commented on capa/features/extractors/dnfile/helpers.py
> +            if table_row is None or table_row in typeref_tb:
We use similar logic in `resolve_nested_typedef_name`. What are your thoughts on adding this check there?

2024-06-07 08:09 UTC, williballenthin commented
@x9090 would you please sign the CLA so that we can merge this PR into capa? We'd love to get it in as part of the v7.1 release soon.

2024-06-11 12:00 UTC, mr-tz commented
friendly bump, @x9090

2024-06-13 08:23 UTC, williballenthin commented
Without the CLA signed, we cannot merge this PR.

I haven't been able to find the file shown in the screenshot on VT, so I can't reproduce this nor reimplement it.

Perhaps we should close this PR until @x9090  returns?

2024-06-13 09:14 UTC, mr-tz commented
yes, let's wait for that or other people raising this issue

2024-06-13 09:14 UTC, closed without merging

2024-06-13 09:50 UTC, r0ny123 commented
> I haven't been able to find the file shown in the screenshot on VT, so I can't reproduce this nor reimplement it.

Can we hunt for it on VT using a YARA rule? :)

2024-06-13 09:52 UTC, williballenthin commented
I did some VTGrep searches for the random looking strings in the screenshot and didn't come up with anything. Have you had any luck?

2024-06-13 09:54 UTC, r0ny123 commented
I mean crafting a YARA for that specific behaviour mentioned. Possible?

2024-06-13 11:02 UTC, williballenthin commented
*maybe* by using the Yara .NET extension. 

It might be easier to manually craft a file by hand: just tweak two bytes (the table references).