readme: avoid scroll on github homepage
mandiant/capa pull request #2538
Opened 2024-12-12 13:17 UTC by williballenthin

### Checklist

- [x] No CHANGELOG update needed

- [x] No new tests needed

- [x] No documentation update needed

2024-12-12 13:18 UTC, williballenthin commented
the default width of the github readme is too narrow to show the first example:

![image](https://github.com/user-attachments/assets/43844cc6-8655-4fbc-9438-917a18f9286d)

so remove a few of the lines and make the columns narrower to fit in this width.

2024-12-12 16:04 UTC, mike-hunhoff requested changes
🚀

2024-12-12 16:04 UTC, mike-hunhoff commented on README.md
> +| execute shell command and capture output  |  c2/shell                                       |
```suggestion
| read and send data from client to server  | c2/file-transfer                               |
| execute shell command and capture output  | c2/shell                                       |
```

2024-12-13 09:35 UTC, mr-tz approved these changes

2024-12-17 13:28 UTC, merged